set dotenv-load

alias b := build
alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --list

check:
    prek run --all-files

audit:
    govulncheck ./...

build:
    go build ./...

run *args:
    go run . {{ args }}

continuous_integration: audit check build
