set dotenv-load

alias a := audit
alias b := build
alias c := check
alias d := doc
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --choose

check:
    prek run --all-files

audit:
    govulncheck ./...

build *args:
    go build ./...

doc *args:
    go doc ./...

run *args:
    go run . {{ args }}

continuous_integration: audit check build doc
