set dotenv-load

alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --list

check:
    uv run -- prek run --all-files

manual:
    uv run -- prek run --stage manual --all-files

run *args:
    uv run -- main.py {{ args }}

continuous_integration: check manual
