set dotenv-load

alias a := audit
alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --choose

bootstrap:
    @command -v uv >/dev/null 2>&1 || { echo "Error: uv is required but was not found in PATH." >&2; exit 1; }
    uv sync --locked

check:
    uvx prek@latest run --all-files

run *args:
    uv run -- main.py {{ args }}

audit:
    uv audit

continuous_integration: bootstrap audit check
