set dotenv-load

[private]
default:
    @just --list

check:
    prek run --all-files

audit:
    prek run audit --all-files

test:
    prek run test --all-files --verbose

build:
    npm run build

run:
    npm start

ci:
    prek run --stage manual --all-files
