set dotenv-load

alias b := build
alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --list

check:
    prek run --all-files

manual:
    prek run --stage manual --all-files

build:
    npm run build

run:
    npm start

continuous_integration: check manual build
