set dotenv-load

[private]
default:
    @just --list

check:
    prek run --all-files

audit:
    prek run audit --all-files

test:
    prek run test --all-files --verbose

run *args:
    deno run main.ts {{ args }}

ci:
    prek run --stage manual --all-files
