set dotenv-load

alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --list

check:
    prek run --all-files

manual:
    prek run --stage manual --all-files

run *args:
    deno run main.ts {{ args }}

continuous_integration: check manual
