set dotenv-load

alias b := build
alias c := check
alias r := run
alias t := test

[private]
default:
    @just --list

check:
    prek run --all-files

manual:
    prek run --stage manual --all-files

audit:
    prek run audit --all-files

test:
    prek run test --all-files --verbose

build *args:
    cargo build --release {{ args }}

run *args:
    cargo run {{ args }}

ci:
    prek run --stage manual --all-files
