set dotenv-load

alias b := build
alias c := check
alias r := run
alias t := test

[private]
default:
    @just --list

check:
    prek run --all-files

manual:
    prek run --stage manual --all-files

test:
    prek run test --all-files

build *args:
    zig build -Doptimize=ReleaseFast {{ args }}

run *args:
    zig build run {{ args }}

ci: check manual build
