set dotenv-load

alias b := build
alias c := check
alias d := doc
alias r := run
alias t := test
alias ci := continuous_integration

[private]
default:
    @just --choose

check:
    prek run --all-files

build *args:
    zig build -Doptimize=ReleaseFast {{ args }}

doc *args:
    zig build docs {{ args }}

run *args:
    zig build run {{ args }}

test *args:
    zig build test {{ args }}

continuous_integration: check build doc test
