set dotenv-load

alias b := build
alias c := check
alias r := run
alias ci := continuous_integration

[private]
default:
    @just --list

check:
    prek run --all-files

build *args:
    zig build -Doptimize=ReleaseFast {{ args }}

run *args:
    zig build run {{ args }}

continuous_integration: check build
